### ISSUE TITLE
jTable DEMO files don't work with new 2.3.1 version

### ISSUE THREAD

**Issue by dwdata** [volosoft/jtable#943]
I downloaded DEMO files and uploaded them to my server to test out your plug-in. For the most part, I was able to have a level of success in generating my own CRUD list and forms.

Then I noticed that a few features were not available (pageSize menu, select Page, filtering, etc...). I realized the DEMO is using version 2.0.0.

I upgraded to version 2.3.1 and my list are not generating properly. It is throwing a few javascript errors:

TypeError: 'undefined' is not a function (evaluating '$(window).on('beforeunload', fTypeError: 'undefined' is not a function (evaluating '$(window).on('beforeunload', function () {
        unloadingPage = true;
    })')
brand_support_resources.php:120

TypeError: 'undefined' is not a function (evaluating '$('#target_container').jtable')

when I switch back to older version 2.0.0, list work fine, but I am missing desired features.

Little help...

Don
